# https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-log.html
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/ubuntu/real-time-weather/weather/log/*.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

# https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html
#--------------------------------- Kafka output -------------------------------
output.kafka:
  hosts: ["10.255.255.6:6667"]
  topic: 'weather'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
